name: ML Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-train-test:
    runs-on: ubuntu-latest

    steps:
      # 1️ Repo clone
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️ Python setup
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3️ Cache dependencies (fast builds)
      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5 Lint (code quality)
      - name: Lint code (flake8)
        run: |
          pip install flake8
          flake8 .

      # 6️ Validate dataset
      - name: Validate dataset
        run: |
          python src/validate_data.py

      # 7️ Run tests
      - name: Run tests
        run: |
          pytest -q

      # 8️ Train model
      - name: Train model
        run: |
          python src/train.py

      # 9️ Evaluate model
      - name: Evaluate model
        run: |
          python src/evaluate.py

      # 10 Upload trained model
      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/

      # 1️1️ Upload metrics
      - name: Upload metrics
        uses: actions/upload-artifact@v4
        with:
          name: model-metrics
          path: models/metrics.txt
